name: CI

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the develop branch
    push:
        branches: [ test ]
    pull_request:
        branches: [ test ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy my nice code
        steps:
            - name: Deploy to OVH hosting
              uses: pitscher/ovh-deploy-hosting-action@v1
              env:
                  OVH_HOSTING_USER: ${{ secrets.OVH_HOSTING_USER }}
                  OVH_HOSTING_PASSWORD: ${{ secrets.OVH_HOSTING_PASSWORD }}
                  OVH_HOSTING_DOMAIN: ssh.clusterXXX.hosting.ovh.net
                  REPOSITORY_NAME: my-repo
                  REPOSITORY_URL: https://github.com/me/my-repo.git
